import { Request, Response } from 'express';
import Course from '../models/Course';
import User from '../models/User';
import Video from '../models/Video';
import Transcript from '../models/Transcript';
import MCQ from '../models/MCQ';
import Progress from '../models/Progress';

// @desc    Create new course
// @route   POST /api/courses
// @access  Private (Teacher only)
export const createCourse = async (req: Request, res: Response): Promise<void> => {
  try {
    const { name, description, category, difficulty } = req.body;
    const teacherId = (req as any).user.id;

    // Validate required fields
    if (!name || !description || !category || !difficulty) {
      res.status(400).json({
        success: false,
        message: 'Please provide all required fields: name, description, category, difficulty',
      });
      return;
    }

    // Validate name length
    if (name.length < 3 || name.length > 100) {
      res.status(400).json({
        success: false,
        message: 'Course name must be between 3 and 100 characters',
      });
      return;
    }

    // Validate description length
    if (description.length < 10 || description.length > 1000) {
      res.status(400).json({
        success: false,
        message: 'Description must be between 10 and 1000 characters',
      });
      return;
    }

    // Validate difficulty
    if (!['beginner', 'intermediate', 'advanced'].includes(difficulty)) {
      res.status(400).json({
        success: false,
        message: 'Difficulty must be beginner, intermediate, or advanced',
      });
      return;
    }

    // Create course (courseId will be auto-generated by pre-save hook)
    const course = await Course.create({
      name,
      description,
      category,
      difficulty,
      teacherId,
    });

    // Populate teacher info
    await course.populate('teacherId', 'name email');

    res.status(201).json({
      success: true,
      course,
    });
  } catch (error: any) {
    console.error('Create course error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error creating course',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined,
    });
  }
};

// @desc    Get all courses (with optional search and pagination)
// @route   GET /api/courses?search=query&page=1&limit=10
// @access  Public
export const getCourses = async (req: Request, res: Response): Promise<void> => {
  try {
    const { search, page = '1', limit = '10' } = req.query;
    let query: any = {};

    if (search) {
      const searchStr = search as string;
      // Search by name (case-insensitive) or Course_ID
      query = {
        $or: [
          { name: { $regex: searchStr, $options: 'i' } },
          { courseId: { $regex: searchStr, $options: 'i' } },
        ],
      };
    }

    // Pagination
    const pageNum = parseInt(page as string, 10);
    const limitNum = parseInt(limit as string, 10);
    const skip = (pageNum - 1) * limitNum;

    // Get total count for pagination metadata
    const total = await Course.countDocuments(query);

    const courses = await Course.find(query)
      .populate('teacherId', 'name email')
      .sort({ createdAt: -1 })
      .skip(skip)
      .limit(limitNum);

    res.status(200).json({
      success: true,
      count: courses.length,
      total,
      page: pageNum,
      pages: Math.ceil(total / limitNum),
      courses,
    });
  } catch (error: any) {
    console.error('Get courses error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error fetching courses',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined,
    });
  }
};

// @desc    Get single course by ID
// @route   GET /api/courses/:courseId
// @access  Public
export const getCourseById = async (req: Request, res: Response): Promise<void> => {
  try {
    const { courseId } = req.params;

    const course = await Course.findById(courseId).populate('teacherId', 'name email profilePicture');

    if (!course) {
      res.status(404).json({
        success: false,
        message: 'Course not found',
      });
      return;
    }

    res.status(200).json({
      success: true,
      course,
    });
  } catch (error: any) {
    console.error('Get course error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error fetching course',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined,
    });
  }
};

// @desc    Delete course
// @route   DELETE /api/courses/:courseId
// @access  Private (Teacher only - must be course owner)
export const deleteCourse = async (req: Request, res: Response): Promise<void> => {
  try {
    const { courseId } = req.params;
    const teacherId = (req as any).user.id;

    const course = await Course.findById(courseId);

    if (!course) {
      res.status(404).json({
        success: false,
        message: 'Course not found',
      });
      return;
    }

    // Verify teacher ownership
    if (course.teacherId.toString() !== teacherId) {
      res.status(403).json({
        success: false,
        message: 'Not authorized to delete this course',
      });
      return;
    }

    // Cascade delete videos, transcripts, MCQs, and progress
    const videos = await Video.find({ courseId: course._id });
    const videoIds = videos.map(v => v._id);
    
    await Video.deleteMany({ courseId: course._id });
    await Transcript.deleteMany({ videoId: { $in: videoIds } });
    await MCQ.deleteMany({ videoId: { $in: videoIds } });
    await Progress.deleteMany({ courseId: course._id });

    await Course.findByIdAndDelete(courseId);

    res.status(200).json({
      success: true,
      message: 'Course deleted successfully',
    });
  } catch (error: any) {
    console.error('Delete course error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error deleting course',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined,
    });
  }
};

// @desc    Update course
// @route   PUT /api/courses/:courseId
// @access  Private (Teacher only - must be course owner)
export const updateCourse = async (req: Request, res: Response): Promise<void> => {
  try {
    const { courseId } = req.params;
    const teacherId = (req as any).user.id;
    const { name, description, category, difficulty, thumbnail } = req.body;

    const course = await Course.findById(courseId);

    if (!course) {
      res.status(404).json({
        success: false,
        message: 'Course not found',
      });
      return;
    }

    // Verify teacher ownership
    if (course.teacherId.toString() !== teacherId) {
      res.status(403).json({
        success: false,
        message: 'Not authorized to update this course',
      });
      return;
    }

    // Update fields
    if (name) course.name = name;
    if (description) course.description = description;
    if (category) course.category = category;
    if (difficulty) course.difficulty = difficulty;
    if (thumbnail) course.thumbnail = thumbnail;

    await course.save();

    res.status(200).json({
      success: true,
      course,
    });
  } catch (error: any) {
    console.error('Update course error:', error);
    res.status(500).json({
      success: false,
      message: 'Server error updating course',
      error: process.env.NODE_ENV === 'development' ? error.message : undefined,
    });
  }
};
